import type { ReactNode, SVGProps } from 'react'
import { AiFillOpenAI } from 'react-icons/ai'
import {
  siAirtable,
  siAnthropic,
  siApple,
  siApplemusic,
  siAsana,
  siBitbucket,
  siBox,
  siBrave,
  siClaude,
  siClickup,
  siCloudflare,
  siConfluence,
  siDevdotto,
  siDiscord,
  siDocker,
  siDropbox,
  siDuckduckgo,
  siEvernote,
  siFacebook,
  siFigma,
  siFirefoxbrowser,
  siFreecodecamp,
  siGithub,
  siGitlab,
  siGmail,
  siGoogle,
  siGooglecalendar,
  siGooglechrome,
  siGoogledrive,
  siGooglemaps,
  siGooglemeet,
  siGooglephotos,
  siIcloud,
  siInstagram,
  siJira,
  siLeetcode,
  siLinear,
  siMedium,
  siNetflix,
  siNotion,
  siNpm,
  siObsidian,
  siPinterest,
  siProducthunt,
  siProtonmail,
  siQuora,
  siReddit,
  siSignal,
  siSoundcloud,
  siSpotify,
  siStackoverflow,
  siStripe,
  siTailwindcss,
  siTelegram,
  siTiktok,
  siTodoist,
  siTrello,
  siTumblr,
  siTwitch,
  siVercel,
  siWhatsapp,
  siWikipedia,
  siWordpress,
  siX,
  siYcombinator,
  siYoutube,
  siZoom,
} from 'simple-icons'

export type BrandIconComponent = (props: SVGProps<SVGSVGElement>) => ReactNode

/** Wraps a simple-icons path string as a component with the same shape as a react-icons icon. */
function fromPath(path: string): BrandIconComponent {
  return (props) => (
    <svg role="img" viewBox="0 0 24 24" fill="currentColor" aria-hidden {...props}>
      <path d={path} />
    </svg>
  )
}

// Ordered by hostname substring; more specific subdomains must come before
// their parent domain (e.g. "drive.google.com" before "google.com").
const DOMAIN_ICONS: Array<[string, BrandIconComponent]> = [
  ['mail.google.com', fromPath(siGmail.path)],
  ['drive.google.com', fromPath(siGoogledrive.path)],
  ['calendar.google.com', fromPath(siGooglecalendar.path)],
  ['maps.google.com', fromPath(siGooglemaps.path)],
  ['photos.google.com', fromPath(siGooglephotos.path)],
  ['meet.google.com', fromPath(siGooglemeet.path)],
  ['chrome.google.com', fromPath(siGooglechrome.path)],
  ['google.com', fromPath(siGoogle.path)],
  ['github.com', fromPath(siGithub.path)],
  ['gitlab.com', fromPath(siGitlab.path)],
  ['bitbucket.org', fromPath(siBitbucket.path)],
  ['reddit.com', fromPath(siReddit.path)],
  ['youtube.com', fromPath(siYoutube.path)],
  ['notion.so', fromPath(siNotion.path)],
  ['notion.com', fromPath(siNotion.path)],
  ['figma.com', fromPath(siFigma.path)],
  ['linear.app', fromPath(siLinear.path)],
  ['spotify.com', fromPath(siSpotify.path)],
  ['netflix.com', fromPath(siNetflix.path)],
  ['twitter.com', fromPath(siX.path)],
  ['x.com', fromPath(siX.path)],
  ['discord.com', fromPath(siDiscord.path)],
  ['discord.gg', fromPath(siDiscord.path)],
  ['whatsapp.com', fromPath(siWhatsapp.path)],
  ['telegram.org', fromPath(siTelegram.path)],
  ['t.me', fromPath(siTelegram.path)],
  ['dropbox.com', fromPath(siDropbox.path)],
  ['medium.com', fromPath(siMedium.path)],
  ['stackoverflow.com', fromPath(siStackoverflow.path)],
  ['instagram.com', fromPath(siInstagram.path)],
  ['facebook.com', fromPath(siFacebook.path)],
  ['trello.com', fromPath(siTrello.path)],
  ['atlassian.net', fromPath(siJira.path)],
  ['confluence', fromPath(siConfluence.path)],
  ['zoom.us', fromPath(siZoom.path)],
  ['twitch.tv', fromPath(siTwitch.path)],
  ['music.apple.com', fromPath(siApplemusic.path)],
  ['icloud.com', fromPath(siIcloud.path)],
  ['apple.com', fromPath(siApple.path)],
  ['wikipedia.org', fromPath(siWikipedia.path)],
  ['npmjs.com', fromPath(siNpm.path)],
  ['docker.com', fromPath(siDocker.path)],
  ['stripe.com', fromPath(siStripe.path)],
  ['vercel.com', fromPath(siVercel.path)],
  ['cloudflare.com', fromPath(siCloudflare.path)],
  ['claude.ai', fromPath(siClaude.path)],
  ['anthropic.com', fromPath(siAnthropic.path)],
  ['console.anthropic.com', fromPath(siAnthropic.path)],
  ['chatgpt.com', AiFillOpenAI],
  ['chat.openai.com', AiFillOpenAI],
  ['platform.openai.com', AiFillOpenAI],
  ['openai.com', AiFillOpenAI],
  ['pinterest.com', fromPath(siPinterest.path)],
  ['tumblr.com', fromPath(siTumblr.path)],
  ['signal.org', fromPath(siSignal.path)],
  ['protonmail.com', fromPath(siProtonmail.path)],
  ['proton.me', fromPath(siProtonmail.path)],
  ['wordpress.com', fromPath(siWordpress.path)],
  ['airtable.com', fromPath(siAirtable.path)],
  ['asana.com', fromPath(siAsana.path)],
  ['clickup.com', fromPath(siClickup.path)],
  ['obsidian.md', fromPath(siObsidian.path)],
  ['todoist.com', fromPath(siTodoist.path)],
  ['evernote.com', fromPath(siEvernote.path)],
  ['box.com', fromPath(siBox.path)],
  ['soundcloud.com', fromPath(siSoundcloud.path)],
  ['tiktok.com', fromPath(siTiktok.path)],
  ['quora.com', fromPath(siQuora.path)],
  ['news.ycombinator.com', fromPath(siYcombinator.path)],
  ['producthunt.com', fromPath(siProducthunt.path)],
  ['dev.to', fromPath(siDevdotto.path)],
  ['freecodecamp.org', fromPath(siFreecodecamp.path)],
  ['leetcode.com', fromPath(siLeetcode.path)],
  ['duckduckgo.com', fromPath(siDuckduckgo.path)],
  ['firefox.com', fromPath(siFirefoxbrowser.path)],
  ['mozilla.org', fromPath(siFirefoxbrowser.path)],
  ['brave.com', fromPath(siBrave.path)],
  ['tailwindcss.com', fromPath(siTailwindcss.path)],
]

export function brandIconFor(url: string): BrandIconComponent | null {
  try {
    const hostname = new URL(url).hostname.replace(/^www\./, '')
    const match = DOMAIN_ICONS.find(([domain]) => hostname.includes(domain))
    return match ? match[1] : null
  } catch {
    return null
  }
}
